networks:
  chanboard-network-dev:
    driver: bridge
  chanboard-network-prod:
    driver: bridge
  chanboard-network-rpi:
    driver: bridge

# x- prefix makes these templates that won't be started
x-chanboard-blob-storage:
  &chanboard-blob-storage
  image: mcr.microsoft.com/azure-storage/azurite:latest
  restart: unless-stopped
  command: "azurite-blob --blobHost 0.0.0.0 -l /data --skipApiVersionCheck"

x-mongo:
  &mongo
  image: mongo:latest
  restart: unless-stopped
  environment:
    MONGO_INITDB_DATABASE: ChanBoardDb