networks:
  chanboard-network-dev:
    driver: bridge
  chanboard-network-prod:
    driver: bridge

services:
  chanboard-blob-storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    restart: unless-stopped
    volumes:
      - ./data
    command: "azurite-blob --blobHost 0.0.0.0 -l /data --skipApiVersionCheck"